### ISSUE TITLE
render Env in case of templated value like {{workingDir}}

### ISSUE THREAD

**Issue by aballiet** [kestra-io/plugin-terraform#5]
### Feature description

We might need to do commands like this :

```YAML
ommands:
   - terraform plan -var-file=terraform.tfvars 2>&1 | tee {{workingDir}}/tfplan.txt
 env:
  GOOGLE_APPLICATION_CREDENTIALS: "{{workingDir}}/sa.json"
```

In order to be able to use workspace files
